[theme]
primaryColor = "#fa7f6f"  # Button & radio button highlight color
backgroundColor = "#282832"  # App background
secondaryBackgroundColor = "#212121"  # Sidebar background
textColor = "#FFFFFF"  # Text color
font = "sans serif"
