[theme]
primaryColor = "#FF4B4B"  # Button & radio button highlight color
backgroundColor = "#000000"  # App background
secondaryBackgroundColor = "#2E3B55"  # Sidebar background
textColor = "#FFFFFF"  # Text color
font = "sans serif"
